# Generated by Django 4.2 on 2023-05-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_store"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="store",
        ),
    ]
