# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/gvanderest/pylama-pre-commit
        rev: 0.1.2
        hooks:
            -   id: pylama
                exclude: '.md'
                args: ['--options', 'pylama.ini']
