version: "3"

services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_DB=checkcashing
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=checkcashingpass
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  database-data: