# Generated by Django 4.2 on 2023-05-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
