# Generated by Django 4.2 on 2023-05-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='store',
        ),
    ]
