# Generated by Django 4.2.1 on 2023-05-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatar',
            new_name='CustomerAvatar',
        ),
        migrations.RenameModel(
            old_name='DriverLicence',
            new_name='CustomerDriverLicence',
        ),
        migrations.RenameModel(
            old_name='Note',
            new_name='CustomerNote',
        ),
    ]
