# Generated by Django 4.2 on 2023-05-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_remove_check_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=6, max_digits=5, null=True),
        ),
    ]
