# Generated by Django 4.2.1 on 2023-05-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0006_alter_check_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='check',
            name='commission',
            field=models.FloatField(blank=True, default=3, null=True),
        ),
    ]
